### ISSUE TITLE
How to build tensorflow and opencv bindings?

### ISSUE THREAD

**Issue by rekado** [wedesoft/aiscm#27]
Hi,

I just packaged aiscm for Guix.  I did add tensorflow (only version 1.9) and OpenCV (version 4.5.4) to the build inputs, but I don't see any bindings for tensorflow or opencv being built.  I also don't see any options in the build system to enable them.  Am I missing something obvious?

~~ Ricardo

**Comment by wedesoft** [comment]
Hi, sorry about that.
You probably used a release version.
Only the development version (git master) uses Tensorflow and OpenCV, because Debian does not have Tensorflow and OpenCV-Aruco functions.
Let me know if you hit any more issues.

Kind regards
Jan

On 26 December 2021 23:25:24 GMT, rekado ***@***.***> wrote:
>Hi,
>
>I just packaged aiscm for Guix.  I did add tensorflow (only version 1.9) and OpenCV (version 4.5.4) to the build inputs, but I don't see any bindings for tensorflow or opencv being built.  I also don't see any options in the build system to enable them.  Am I missing something obvious?
>
>~~ Ricardo
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/wedesoft/aiscm/issues/27
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by rekado** [comment]
Ah, that makes sense.  Thank you for the quick response!

I'll try to package the latest git commit as `guile-aiscm-next` in Guix, but before that I'll have to adjust our `tensorflow` package to ensure that the C bindings are in fact built.  In the meantime `guile-aiscm` is available in Guix now.
